### ISSUE TITLE
Behavior when running outside of Polyaxon

### ISSUE THREAD

**Issue by waltsims** [polyaxon/polyaxon-helper#3]
I would recommend that these methods have a defined behavior when running outside of the Polyaxon framework ( e.g. is_connected == False or graceful failure when trying to record metrics)

current output when trying to record a metric without a cluster is:

`/lib/python3.5/site-packages/polyaxon_helper/__init__.py", line 93, in send_metrics
    experiment.log_metrics(**metrics)
AttributeError: 'NoneType' object has no attribute 'log_metrics'`

Perhaps the methods could be overwritten in the "NoneType-case"? Or the package offers a method is_connected?

**Comment by mouradmourafiq** [comment]
Please look at the [docs](https://docs.polyaxon.com/references/tracking-api/#disabling-polyaxon-tracking-without-changing-the-code) for disabling Polyaxon in your scripts.

Basically you can have a `POLYAXON_NO_OP` env var set to True, and all polyaxon calls will be ignored. (this requires a polyaxon-client or polyaxon-helper > 0.3.8)

**Comment by waltsims** [comment]
wow perfect thanks for the fast reply.
